apiVersion: apiaccesscontrol.oci.m.upbound.io/v1alpha1
kind: PrivilegedApiControl
metadata:
  annotations:
    meta.upbound.io/example-id: apiaccesscontrol/v1alpha1/privilegedapicontrol
  labels:
    testing.upbound.io/example-name: test_privileged_api_control
  name: test-privileged-api-control
  namespace: upbound-system
spec:
  forProvider:
    approverGroupIdList: ${var.privileged_api_control_approver_group_id_list}
    approverGroupLevelList:
    - groupIdSelector:
        matchLabels:
          testing.upbound.io/example-name: test_group
      groupLevel: ${var.privileged_api_control_approver_group_level_list_group_level}
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    definedTags:
      Operations.CostCenter: "42"
    description: ${var.privileged_api_control_description}
    displayName: ${var.privileged_api_control_display_name}
    freeformTags:
      Department: Finance
    notificationTopicIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_notification_topic
    numberOfApprovers: ${var.privileged_api_control_number_of_approvers}
    privilegedOperationList:
    - apiNameSelector:
        matchLabels:
          testing.upbound.io/example-name: test_api
      attributeNames: ${var.privileged_api_control_privileged_operation_list_attribute_names}
      entityType: ${var.privileged_api_control_privileged_operation_list_entity_type}
    resourceType: ${var.privileged_api_control_resource_type}
    resources: ${var.privileged_api_control_resources}
