/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Alarm) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CaptureFilter) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Vtap) Hub() {}
