apiVersion: database.oci.m.upbound.io/v1alpha1
kind: DbHome
metadata:
  annotations:
    meta.upbound.io/example-id: database/v1alpha1/dbhome
  labels:
    testing.upbound.io/example-name: test_db_home
  name: test-db-home
  namespace: upbound-system
spec:
  forProvider:
    database:
    - adminPasswordSecretRef:
        key: example-key
        name: example-secret
      backupIdSelector:
        matchLabels:
          testing.upbound.io/example-name: test_backup
      backupTdePasswordSecretRef:
        key: example-key
        name: example-secret
      characterSet: ${var.db_home_database_character_set}
      databaseIdSelector:
        matchLabels:
          testing.upbound.io/example-name: test_database
      databaseSoftwareImageIdSelector:
        matchLabels:
          testing.upbound.io/example-name: test_database_software_image
      dbBackupConfig:
      - autoBackupEnabled: ${var.db_home_database_db_backup_config_auto_backup_enabled}
        autoBackupWindow: ${var.db_home_database_db_backup_config_auto_backup_window}
        autoFullBackupDay: ${var.db_home_database_db_backup_config_auto_full_backup_day}
        autoFullBackupWindow: ${var.db_home_database_db_backup_config_auto_full_backup_window}
        backupDeletionPolicy: ${var.db_home_database_db_backup_config_backup_deletion_policy}
        backupDestinationDetails:
        - backupRetentionPolicyOnTerminate: ${var.db_home_database_db_backup_config_backup_destination_details_backup_retention_policy_on_terminate}
          dbrsPolicyIdSelector:
            matchLabels:
              testing.upbound.io/example-name: test_policy
          id: ${var.db_home_database_db_backup_config_backup_destination_details_id}
          isRemote: ${var.db_home_database_db_backup_config_backup_destination_details_is_remote}
          isRetentionLockEnabled: ${var.db_home_database_db_backup_config_backup_destination_details_is_retention_lock_enabled}
          remoteRegion: ${var.db_home_database_db_backup_config_backup_destination_details_remote_region}
          tdeWalletBackupDestination:
          - backupDestinationIdSelector:
              matchLabels:
                testing.upbound.io/example-name: test_backup_destination
            backupDestinationType: ${var.db_home_database_db_backup_config_backup_destination_details_tde_wallet_backup_destination_backup_destination_type}
          type: ${var.db_home_database_db_backup_config_backup_destination_details_type}
        recoveryWindowInDays: ${var.db_home_database_db_backup_config_recovery_window_in_days}
        runImmediateFullBackup: ${var.db_home_database_db_backup_config_run_immediate_full_backup}
      dbName: ${var.db_home_database_db_name}
      dbWorkload: ${var.db_home_database_db_workload}
      definedTags: ${var.db_home_database_defined_tags}
      encryptionKeyLocationDetails:
      - azureEncryptionKeyIdSelector:
          matchLabels:
            testing.upbound.io/example-name: test_key
        hsmPasswordSecretRef:
          key: example-key
          name: example-secret
        providerType: ${var.db_home_database_encryption_key_location_details_provider_type}
      freeformTags: ${var.db_home_database_freeform_tags}
      keyStoreIdSelector:
        matchLabels:
          testing.upbound.io/example-name: test_key_store
      kmsKeyIdSelector:
        matchLabels:
          testing.upbound.io/example-name: test_key
      kmsKeyVersionIdSelector:
        matchLabels:
          testing.upbound.io/example-name: test_key_version
      managed_software_update_details:
      - is_enrolled: ${var.db_home_database_managed_software_update_details_is_enrolled}
        preference_details:
        - days_of_week: ${var.db_home_database_managed_software_update_details_preference_details_days_of_week}
          hour_of_day: ${var.db_home_database_managed_software_update_details_preference_details_hour_of_day}
          update_mode: ${var.db_home_database_managed_software_update_details_preference_details_update_mode}
          version_scheme_details:
          - major_version: ${var.db_home_database_managed_software_update_details_preference_details_version_scheme_details_major_version}
            source: ${var.db_home_database_managed_software_update_details_preference_details_version_scheme_details_source}
            version_preference: ${var.db_home_database_managed_software_update_details_preference_details_version_scheme_details_version_preference}
      ncharacterSet: ${var.db_home_database_ncharacter_set}
      pdbName: ${var.db_home_database_pdb_name}
      pluggableDatabases: ${var.db_home_database_pluggable_databases}
      recoveryApplianceVpcPasswordSecretRef:
        key: example-key
        name: example-secret
      source_encryption_key_location_details:
      - azure_encryption_key_id: ${oci_kms_key.test_key.id}
        hsm_password: ${var.db_home_database_source_encryption_key_location_details_hsm_password}
        provider_type: ${var.db_home_database_source_encryption_key_location_details_provider_type}
      storageSizeDetails:
      - dataStorageSizeInGb: ${var.db_home_database_storage_size_details_data_storage_size_in_gb}
        recoStorageSizeInGbs: ${var.db_home_database_storage_size_details_reco_storage_size_in_gbs}
      tdeWalletPasswordSecretRef:
        key: example-key
        name: example-secret
      timeStampForPointInTimeRecovery: ${var.db_home_database_time_stamp_for_point_in_time_recovery}
      vaultIdSelector:
        matchLabels:
          testing.upbound.io/example-name: test_vault
      vmClusterIdSelector:
        matchLabels:
          testing.upbound.io/example-name: test_vm_cluster
    databaseSoftwareImageIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_database_software_image
    dbSystemIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_db_system
    dbVersion:
    - {}
    definedTags: ${var.db_home_defined_tags}
    displayName: ${var.db_home_display_name}
    freeformTags:
      Department: Finance
    isDesupportedVersion: ${var.db_home_is_desupported_version}
    isUnifiedAuditingEnabled: ${var.db_home_is_unified_auditing_enabled}
    kmsKeyIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_key
    kmsKeyVersionIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_key_version
    source: ${var.db_home_source}
    vmClusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_vm_cluster
