apiVersion: database.oci.m.upbound.io/v1alpha1
kind: VmCluster
metadata:
  annotations:
    meta.upbound.io/example-id: database/v1alpha1/vmcluster
  labels:
    testing.upbound.io/example-name: test_vm_cluster
  name: test-vm-cluster
  namespace: upbound-system
spec:
  forProvider:
    cloudAutomationUpdateDetails:
    - applyUpdateTimePreference:
      - applyUpdatePreferredEndTime: ${var.vm_cluster_cloud_automation_update_details_apply_update_time_preference_apply_update_preferred_end_time}
        applyUpdatePreferredStartTime: ${var.vm_cluster_cloud_automation_update_details_apply_update_time_preference_apply_update_preferred_start_time}
      freezePeriod:
      - freezePeriodEndTime: ${var.vm_cluster_cloud_automation_update_details_freeze_period_freeze_period_end_time}
        freezePeriodStartTime: ${var.vm_cluster_cloud_automation_update_details_freeze_period_freeze_period_start_time}
      isEarlyAdoptionEnabled: ${var.vm_cluster_cloud_automation_update_details_is_early_adoption_enabled}
      isFreezePeriodEnabled: ${var.vm_cluster_cloud_automation_update_details_is_freeze_period_enabled}
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    cpuCoreCount: ${var.vm_cluster_cpu_core_count}
    dataCollectionOptions:
    - isDiagnosticsEventsEnabled: ${var.vm_cluster_data_collection_options_is_diagnostics_events_enabled}
      isHealthMonitoringEnabled: ${var.vm_cluster_data_collection_options_is_health_monitoring_enabled}
      isIncidentLogsEnabled: ${var.vm_cluster_data_collection_options_is_incident_logs_enabled}
    dataStoragePercentage: ${var.vm_cluster_data_storage_percentage}
    dataStorageSizeInTbs: ${var.vm_cluster_data_storage_size_in_tbs}
    dbNodeStorageSizeInGbs: ${var.vm_cluster_db_node_storage_size_in_gbs}
    dbServers: ${var.vm_cluster_db_servers}
    definedTags: ${var.vm_cluster_defined_tags}
    displayName: ${var.vm_cluster_display_name}
    exadataInfrastructureIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_exadata_infrastructure
    exascaleDbStorageVaultIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_exascale_db_storage_vault
    fileSystemConfigurationDetails:
    - fileSystemSizeGb: ${var.vm_cluster_file_system_configuration_details_file_system_size_gb}
      mountPoint: ${var.vm_cluster_file_system_configuration_details_mount_point}
    freeformTags:
      Department: Finance
    giVersion: ${var.vm_cluster_gi_version}
    isLocalBackupEnabled: ${var.vm_cluster_is_local_backup_enabled}
    isSparseDiskgroupEnabled: ${var.vm_cluster_is_sparse_diskgroup_enabled}
    licenseModel: ${var.vm_cluster_license_model}
    memorySizeInGbs: ${var.vm_cluster_memory_size_in_gbs}
    recoStoragePercentage: ${var.vm_cluster_reco_storage_percentage}
    sparseStoragePercentage: ${var.vm_cluster_sparse_storage_percentage}
    sshPublicKeys: ${var.vm_cluster_ssh_public_keys}
    systemVersion: ${var.vm_cluster_system_version}
    timeZone: ${var.vm_cluster_time_zone}
    updateDetails:
    - updateAction: ${var.vm_cluster_update_details_update_action}
      updateId: ${var.vm_cluster_update_details_update_id}
      updateMode: ${var.vm_cluster_update_details_update_mode}
    vmBackupStorageType: ${var.vm_cluster_vm_backup_storage_type}
    vmClusterNetworkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_vm_cluster_network
    vmClusterType: ${var.vm_cluster_vm_cluster_type}
    vmFileSystemStorageType: ${var.vm_cluster_vm_file_system_storage_type}
