/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type HostedApplicationStorageInitParameters struct {

	// (Updatable) The compartment OCID to create the hosted application in.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/identity/v1alpha1.Compartment
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.Reference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.Selector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags.  Example: {"Operations.CostCenter": "42"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// An optional description of the hosted application.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A user-friendly name. Does not have to be unique, and it's changeable.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags.  Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// type like Cache, Postgresql and ADB.
	StorageType *string `json:"storageType,omitempty" tf:"storage_type,omitempty"`
}

type HostedApplicationStorageObservation struct {

	// A list of application OCID.
	ApplicationIds []*string `json:"applicationIds,omitempty" tf:"application_ids,omitempty"`

	// (Updatable) The compartment OCID to create the hosted application in.
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags.  Example: {"Operations.CostCenter": "42"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// An optional description of the hosted application.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A user-friendly name. Does not have to be unique, and it's changeable.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags.  Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// The OCID of the hosted application storage.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A message describing the current state of the hosted application storage in more detail that can provide actionable information.
	LifecycleDetails *string `json:"lifecycleDetails,omitempty" tf:"lifecycle_details,omitempty"`

	// The current state of the hosted application storage.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// type like Cache, Postgresql and ADB.
	StorageType *string `json:"storageType,omitempty" tf:"storage_type,omitempty"`

	// System tags for this resource. Each key is predefined and scoped to a namespace.  Example: {"orcl-cloud.free-tier-retained": "true"}
	// +mapType=granular
	SystemTags map[string]*string `json:"systemTags,omitempty" tf:"system_tags,omitempty"`

	// The date and time the hosted application was created, in the format defined by RFC 3339
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// The date and time the hosted application was updated, in the format defined by RFC 3339
	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`
}

type HostedApplicationStorageParameters struct {

	// (Updatable) The compartment OCID to create the hosted application in.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/identity/v1alpha1.Compartment
	// +kubebuilder:validation:Optional
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.Reference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.Selector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags.  Example: {"Operations.CostCenter": "42"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// An optional description of the hosted application.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A user-friendly name. Does not have to be unique, and it's changeable.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags.  Example: {"Department": "Finance"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// type like Cache, Postgresql and ADB.
	// +kubebuilder:validation:Optional
	StorageType *string `json:"storageType,omitempty" tf:"storage_type,omitempty"`
}

// HostedApplicationStorageSpec defines the desired state of HostedApplicationStorage
type HostedApplicationStorageSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     HostedApplicationStorageParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider HostedApplicationStorageInitParameters `json:"initProvider,omitempty"`
}

// HostedApplicationStorageStatus defines the observed state of HostedApplicationStorage.
type HostedApplicationStorageStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        HostedApplicationStorageObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// HostedApplicationStorage is the Schema for the HostedApplicationStorages API. Provides the Hosted Application Storage resource in Oracle Cloud Infrastructure Generative AI service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type HostedApplicationStorage struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.storageType) || (has(self.initProvider) && has(self.initProvider.storageType))",message="spec.forProvider.storageType is a required parameter"
	Spec   HostedApplicationStorageSpec   `json:"spec"`
	Status HostedApplicationStorageStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// HostedApplicationStorageList contains a list of HostedApplicationStorages
type HostedApplicationStorageList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []HostedApplicationStorage `json:"items"`
}

// Repository type metadata.
var (
	HostedApplicationStorage_Kind             = "HostedApplicationStorage"
	HostedApplicationStorage_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: HostedApplicationStorage_Kind}.String()
	HostedApplicationStorage_KindAPIVersion   = HostedApplicationStorage_Kind + "." + CRDGroupVersion.String()
	HostedApplicationStorage_GroupVersionKind = CRDGroupVersion.WithKind(HostedApplicationStorage_Kind)
)

func init() {
	SchemeBuilder.Register(&HostedApplicationStorage{}, &HostedApplicationStorageList{})
}
