/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type BdsCapacityReservationInitParameters struct {

	// (Updatable) The OCID of the compartment in which to create the BDS capacity reservation.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/identity/v1alpha1.Compartment
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.NamespacedReference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.NamespacedSelector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// (Updatable) Compute capacity reservation ID mappings by domain. For a multi-AD region, domain1, domain2, and domain3 correspond to AD1, AD2, and AD3 respectively. For a single-AD region, domain1, domain2, and domain3 correspond to FD1, FD2, and FD3 respectively.
	ComputeCapacityReservations []ComputeCapacityReservationsInitParameters `json:"computeCapacityReservations,omitempty" tf:"compute_capacity_reservations,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For example, {"foo-namespace": {"bar-key": "value"}}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) A user-friendly name for the BDS capacity reservation.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Simple key-value pair that is applied without any predefined name, type, or scope. Exists for cross-compatibility only. For example, {"bar-key": "value"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`
}

type BdsCapacityReservationObservation struct {

	// (Updatable) The OCID of the compartment in which to create the BDS capacity reservation.
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// (Updatable) Compute capacity reservation ID mappings by domain. For a multi-AD region, domain1, domain2, and domain3 correspond to AD1, AD2, and AD3 respectively. For a single-AD region, domain1, domain2, and domain3 correspond to FD1, FD2, and FD3 respectively.
	ComputeCapacityReservations []ComputeCapacityReservationsObservation `json:"computeCapacityReservations,omitempty" tf:"compute_capacity_reservations,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For example, {"foo-namespace": {"bar-key": "value"}}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) A user-friendly name for the BDS capacity reservation.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Simple key-value pair that is applied without any predefined name, type, or scope. Exists for cross-compatibility only. For example, {"bar-key": "value"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// The OCID of the BDS capacity reservation.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The lifecycle state of the BDS capacity reservation.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// Usage of system tag keys. These predefined keys are scoped to namespaces.
	// +mapType=granular
	SystemTags map[string]*string `json:"systemTags,omitempty" tf:"system_tags,omitempty"`

	// The time the BDS capacity reservation was created, shown as an RFC 3339 formatted datetime string.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// The time the BDS capacity reservation was updated, shown as an RFC 3339 formatted datetime string.
	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`
}

type BdsCapacityReservationParameters struct {

	// (Updatable) The OCID of the compartment in which to create the BDS capacity reservation.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/identity/v1alpha1.Compartment
	// +kubebuilder:validation:Optional
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.NamespacedReference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.NamespacedSelector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// (Updatable) Compute capacity reservation ID mappings by domain. For a multi-AD region, domain1, domain2, and domain3 correspond to AD1, AD2, and AD3 respectively. For a single-AD region, domain1, domain2, and domain3 correspond to FD1, FD2, and FD3 respectively.
	// +kubebuilder:validation:Optional
	ComputeCapacityReservations []ComputeCapacityReservationsParameters `json:"computeCapacityReservations,omitempty" tf:"compute_capacity_reservations,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For example, {"foo-namespace": {"bar-key": "value"}}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) A user-friendly name for the BDS capacity reservation.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Simple key-value pair that is applied without any predefined name, type, or scope. Exists for cross-compatibility only. For example, {"bar-key": "value"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`
}

type ComputeCapacityReservationsInitParameters struct {

	// (Updatable) Compute capacity reservation OCID corresponding to AD1 for a multi-AD region or FD1 for a single-AD region.
	Domain1ReservationID *string `json:"domain1reservationId,omitempty" tf:"domain1reservation_id,omitempty"`

	// (Updatable) Compute capacity reservation OCID corresponding to AD2 for a multi-AD region or FD2 for a single-AD region.
	Domain2ReservationID *string `json:"domain2reservationId,omitempty" tf:"domain2reservation_id,omitempty"`

	// (Updatable) Compute capacity reservation OCID corresponding to AD3 for a multi-AD region or FD3 for a single-AD region.
	Domain3ReservationID *string `json:"domain3reservationId,omitempty" tf:"domain3reservation_id,omitempty"`
}

type ComputeCapacityReservationsObservation struct {

	// (Updatable) Compute capacity reservation OCID corresponding to AD1 for a multi-AD region or FD1 for a single-AD region.
	Domain1ReservationID *string `json:"domain1reservationId,omitempty" tf:"domain1reservation_id,omitempty"`

	// (Updatable) Compute capacity reservation OCID corresponding to AD2 for a multi-AD region or FD2 for a single-AD region.
	Domain2ReservationID *string `json:"domain2reservationId,omitempty" tf:"domain2reservation_id,omitempty"`

	// (Updatable) Compute capacity reservation OCID corresponding to AD3 for a multi-AD region or FD3 for a single-AD region.
	Domain3ReservationID *string `json:"domain3reservationId,omitempty" tf:"domain3reservation_id,omitempty"`
}

type ComputeCapacityReservationsParameters struct {

	// (Updatable) Compute capacity reservation OCID corresponding to AD1 for a multi-AD region or FD1 for a single-AD region.
	// +kubebuilder:validation:Optional
	Domain1ReservationID *string `json:"domain1reservationId,omitempty" tf:"domain1reservation_id,omitempty"`

	// (Updatable) Compute capacity reservation OCID corresponding to AD2 for a multi-AD region or FD2 for a single-AD region.
	// +kubebuilder:validation:Optional
	Domain2ReservationID *string `json:"domain2reservationId,omitempty" tf:"domain2reservation_id,omitempty"`

	// (Updatable) Compute capacity reservation OCID corresponding to AD3 for a multi-AD region or FD3 for a single-AD region.
	// +kubebuilder:validation:Optional
	Domain3ReservationID *string `json:"domain3reservationId,omitempty" tf:"domain3reservation_id,omitempty"`
}

// BdsCapacityReservationSpec defines the desired state of BdsCapacityReservation
type BdsCapacityReservationSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            BdsCapacityReservationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BdsCapacityReservationInitParameters `json:"initProvider,omitempty"`
}

// BdsCapacityReservationStatus defines the observed state of BdsCapacityReservation.
type BdsCapacityReservationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BdsCapacityReservationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// BdsCapacityReservation is the Schema for the BdsCapacityReservations API. Provides the Bds Capacity Reservation resource in Oracle Cloud Infrastructure Big Data Service service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,oci}
type BdsCapacityReservation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.computeCapacityReservations) || (has(self.initProvider) && has(self.initProvider.computeCapacityReservations))",message="spec.forProvider.computeCapacityReservations is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	Spec   BdsCapacityReservationSpec   `json:"spec"`
	Status BdsCapacityReservationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BdsCapacityReservationList contains a list of BdsCapacityReservations
type BdsCapacityReservationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BdsCapacityReservation `json:"items"`
}

// Repository type metadata.
var (
	BdsCapacityReservation_Kind             = "BdsCapacityReservation"
	BdsCapacityReservation_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: BdsCapacityReservation_Kind}.String()
	BdsCapacityReservation_KindAPIVersion   = BdsCapacityReservation_Kind + "." + CRDGroupVersion.String()
	BdsCapacityReservation_GroupVersionKind = CRDGroupVersion.WithKind(BdsCapacityReservation_Kind)
)

func init() {
	SchemeBuilder.Register(&BdsCapacityReservation{}, &BdsCapacityReservationList{})
}
