/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *AutoScalingConfiguration) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BdsCapacityReport) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BdsCapacityReservation) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BdsClusterAdminPasswordResetAction) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BdsInstance) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BdsInstanceApiKey) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BdsInstanceBdsCapacityReservationConfiguration) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BdsInstanceBdsCertificateConfiguration) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BdsInstanceExecuteBootstrapScriptAction) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BdsInstanceIdentityConfiguration) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BdsInstanceMetastoreConfig) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BdsInstanceNodeBackup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BdsInstanceNodeBackupConfiguration) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BdsInstanceNodeReplaceConfiguration) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BdsInstanceOperationCertificateManagementsManagement) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BdsInstanceOsPatchAction) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BdsInstancePatchAction) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BdsInstanceReplaceNodeAction) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BdsInstanceResourcePrincipalConfiguration) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BdsInstanceSoftwareUpdateAction) Hub() {}
