apiVersion: networkconnectivity.oci.upbound.io/v1alpha1
kind: DrgRouteTableRouteRule
metadata:
  annotations:
    meta.upbound.io/example-id: networkconnectivity/v1alpha1/drgroutetablerouterule
  labels:
    testing.upbound.io/example-name: test_drg_route_table_route_rule
  name: test-drg-route-table-route-rule
spec:
  forProvider:
    destination: ${var.drg_route_table_route_rule_route_rules_destination}
    destinationType: ${var.drg_route_table_route_rule_route_rules_destination_type}
    drgRouteTableIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_drg_route_table
    nextHopDrgAttachmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_drg_attachment
