apiVersion: core.oci.upbound.io/v1alpha1
kind: DHCPOptions
metadata:
  annotations:
    meta.upbound.io/example-id: core/v1alpha1/dhcpoptions
  labels:
    testing.upbound.io/example-name: test_dhcp_options
  name: test-dhcp-options
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    displayName: ${var.dhcp_options_display_name}
    options:
    - serverType: VcnLocalPlusInternet
      type: DomainNameServer
    - searchDomainNames:
      - test.com
      type: SearchDomain
    vcnIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_vcn

---

