apiVersion: core.oci.upbound.io/v1alpha1
kind: InstancePool
metadata:
  annotations:
    meta.upbound.io/example-id: core/v1alpha1/instancepool
  labels:
    testing.upbound.io/example-name: test_instance_pool
  name: test-instance-pool
spec:
  forProvider:
    compartmentId: ${var.compartment_id}
    definedTags:
      Operations.CostCenter: "42"
    displayName: ${var.instance_pool_display_name}
    freeformTags:
      Department: Finance
    instanceConfigurationId: ${oci_core_instance_configuration.test_instance_configuration.id}
    loadBalancers:
    - backendSetName: ${var.backend_set_name}
      loadBalancerId: ${oci_load_balancer_load_balancer.test_load_balancer.id}
      port: ${var.instance_pool_load_balancers_port}
      vnicSelection: ${var.instance_pool_load_balancers_vnic_selection}
    placementConfigurations:
    - availabilityDomain: ${var.instance_pool_placement_configurations_availability_domain}
      faultDomains: ${var.instance_pool_placement_configurations_fault_domains}
      primarySubnetId: ${oci_core_subnet.test_subnet.id}
      secondaryVnicSubnets:
      - displayName: ${var.instance_pool_placement_configurations_secondary_vnic_subnets_display_name}
        subnetId: ${oci_core_subnet.test_subnet.id}
    size: ${var.instance_pool_size}

---

