/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Cpe) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CrossConnect) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CrossConnectGroup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Drg) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DrgAttachment) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DrgAttachmentManagement) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DrgAttachmentsList) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DrgRouteDistribution) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DrgRouteDistributionStatement) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DrgRouteTable) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DrgRouteTableRouteRule) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Ipsec) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *IpsecConnectionTunnelManagement) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VirtualCircuit) Hub() {}
