apiVersion: monitoring.oci.upbound.io/v1alpha1
kind: Alarm
metadata:
  annotations:
    meta.upbound.io/example-id: monitoring/v1alpha1/alarm
  labels:
    testing.upbound.io/example-name: test_alarm
  name: test-alarm
spec:
  forProvider:
    alarmSummary: ${var.alarm_alarm_summary}
    body: ${var.alarm_body}
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    definedTags:
      Operations.CostCenter: "42"
    destinations:
    - ${oci_ons_notification_topic.test_notification_topic.id}
    displayName: ${var.alarm_display_name}
    evaluationSlackDuration: ${var.alarm_evaluation_slack_duration}
    freeformTags:
      Department: Finance
    isEnabled: ${var.alarm_is_enabled}
    isNotificationsPerMetricDimensionEnabled: ${var.alarm_is_notifications_per_metric_dimension_enabled}
    messageFormat: ${var.alarm_message_format}
    metricCompartmentIdInSubtree: ${var.alarm_metric_compartment_id_in_subtree}
    metricCompartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    namespace: ${var.alarm_namespace}
    notificationTitle: ${var.alarm_notification_title}
    notificationVersion: ${var.alarm_notification_version}
    overrides:
    - body: ${var.alarm_overrides_body}
      pendingDuration: ${var.alarm_overrides_pending_duration}
      query: ${var.alarm_overrides_query}
      ruleName: ${oci_events_rule.test_rule.name}
      severity: ${var.alarm_overrides_severity}
    pendingDuration: ${var.alarm_pending_duration}
    query: ${var.alarm_query}
    repeatNotificationDuration: ${var.alarm_repeat_notification_duration}
    resolution: ${var.alarm_resolution}
    resourceGroup: ${var.alarm_resource_group}
    ruleName: ${oci_events_rule.test_rule.name}
    severity: ${var.alarm_severity}
    suppression:
    - description: ${var.alarm_suppression_description}
      timeSuppressFrom: ${var.alarm_suppression_time_suppress_from}
      timeSuppressUntil: ${var.alarm_suppression_time_suppress_until}
