/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type TagNamespaceObservation struct {

	// The OCID of the tag namespace.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The tagnamespace's current state. After creating a tagnamespace, make sure its lifecycleState is ACTIVE before using it. After retiring a tagnamespace, make sure its lifecycleState is INACTIVE before using it.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// Date and time the tag namespace was created, in the format defined by RFC3339. Example: 2016-08-25T21:10:29.600Z
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`
}

type TagNamespaceParameters struct {

	// (Updatable) The OCID of the tenancy containing the tag namespace.
	// +crossplane:generate:reference:type=Compartment
	// +kubebuilder:validation:Optional
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.Reference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.Selector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags.  Example: {"Operations.CostCenter": "42"}
	// +kubebuilder:validation:Optional
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) The description you assign to the tag namespace during creation.
	// +kubebuilder:validation:Required
	Description *string `json:"description" tf:"description,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags.  Example: {"Department": "Finance"}
	// +kubebuilder:validation:Optional
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// (Updatable) Whether the tag namespace is retired. For more information, see Retiring Key Definitions and Namespace Definitions.
	// +kubebuilder:validation:Optional
	IsRetired *bool `json:"isRetired,omitempty" tf:"is_retired,omitempty"`

	// The name you assign to the tag namespace during creation. It must be unique across all tag namespaces in the tenancy and cannot be changed.
	// +kubebuilder:validation:Required
	Name *string `json:"name" tf:"name,omitempty"`
}

// TagNamespaceSpec defines the desired state of TagNamespace
type TagNamespaceSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TagNamespaceParameters `json:"forProvider"`
}

// TagNamespaceStatus defines the observed state of TagNamespace.
type TagNamespaceStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TagNamespaceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// TagNamespace is the Schema for the TagNamespaces API. Provides the Tag Namespace resource in Oracle Cloud Infrastructure Identity service
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type TagNamespace struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TagNamespaceSpec   `json:"spec"`
	Status            TagNamespaceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TagNamespaceList contains a list of TagNamespaces
type TagNamespaceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TagNamespace `json:"items"`
}

// Repository type metadata.
var (
	TagNamespace_Kind             = "TagNamespace"
	TagNamespace_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TagNamespace_Kind}.String()
	TagNamespace_KindAPIVersion   = TagNamespace_Kind + "." + CRDGroupVersion.String()
	TagNamespace_GroupVersionKind = CRDGroupVersion.WithKind(TagNamespace_Kind)
)

func init() {
	SchemeBuilder.Register(&TagNamespace{}, &TagNamespaceList{})
}
