apiVersion: file.oci.upbound.io/v1alpha1
kind: StorageReplication
metadata:
  annotations:
    meta.upbound.io/example-id: file/v1alpha1/storagereplication
  labels:
    testing.upbound.io/example-name: test_replication
  name: test-replication
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    definedTags:
      Operations.CostCenter: "42"
    displayName: ${var.replication_display_name}
    freeformTags:
      Department: Finance
    replicationInterval: ${var.replication_replication_interval}
    sourceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_source
    targetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_target
