apiVersion: networking.oci.upbound.io/v1alpha1
kind: InternetGateway
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/internetgateway
  labels:
    testing.upbound.io/example-name: test_internet_gateway
  name: test-internet-gateway
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    definedTags:
      Operations.CostCenter: "42"
    displayName: ${var.internet_gateway_display_name}
    enabled: ${var.internet_gateway_enabled}
    freeformTags:
      Department: Finance
    routeTableId: ${oci_core_route_table.test_route_table.id}
    vcnIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_vcn
