apiVersion: networking.oci.upbound.io/v1alpha1
kind: Vlan
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/vlan
  labels:
    testing.upbound.io/example-name: test_vlan
  name: test-vlan
spec:
  forProvider:
    availabilityDomain: ${var.vlan_availability_domain}
    cidrBlock: ${var.vlan_cidr_block}
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    definedTags:
      Operations.CostCenter: "42"
    displayName: ${var.vlan_display_name}
    freeformTags:
      Department: Finance
    nsgIds: ${var.vlan_nsg_ids}
    routeTableId: ${oci_core_route_table.test_route_table.id}
    vcnIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_vcn
    vlanTag: ${var.vlan_vlan_tag}
