apiVersion: networking.oci.upbound.io/v1alpha1
kind: VnicAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/vnicattachment
  labels:
    testing.upbound.io/example-name: test_vnic_attachment
  name: test-vnic-attachment
spec:
  forProvider:
    createVnicDetails:
    - assignIpv6Ip: ${var.vnic_attachment_create_vnic_details_assign_ipv6ip}
      assignPrivateDnsRecord: ${var.vnic_attachment_create_vnic_details_assign_private_dns_record}
      assignPublicIp: ${var.vnic_attachment_create_vnic_details_assign_public_ip}
      definedTags: ${var.vnic_attachment_create_vnic_details_defined_tags}
      displayName: ${var.vnic_attachment_create_vnic_details_display_name}
      freeformTags: ${var.vnic_attachment_create_vnic_details_freeform_tags}
      hostnameLabel: ${var.vnic_attachment_create_vnic_details_hostname_label}
      ipv6addressIpv6SubnetCidrPairDetails: ${var.vnic_attachment_create_vnic_details_ipv6address_ipv6subnet_cidr_pair_details}
      nsgIds: ${var.vnic_attachment_create_vnic_details_nsg_ids}
      privateIp: ${var.vnic_attachment_create_vnic_details_private_ip}
      securityAttributes: ${var.vnic_attachment_create_vnic_details_security_attributes}
      skipSourceDestCheck: ${var.vnic_attachment_create_vnic_details_skip_source_dest_check}
      subnetId: ${oci_core_subnet.test_subnet.id}
      vlanId: ${oci_core_vlan.test_vlan.id}
    displayName: ${var.vnic_attachment_display_name}
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_instance
    nicIndex: ${var.vnic_attachment_nic_index}
