apiVersion: aidataplatform.oci.upbound.io/v1alpha1
kind: AiDataPlatform
metadata:
  annotations:
    meta.upbound.io/example-id: aidataplatform/v1alpha1/aidataplatform
  labels:
    testing.upbound.io/example-name: test_ai_data_platform
  name: test-ai-data-platform
spec:
  forProvider:
    aiDataPlatformType: ${var.ai_data_platform_ai_data_platform_type}
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    defaultWorkspaceNameSelector:
      matchLabels:
        testing.upbound.io/example-name: test_workspace
    definedTags:
      Operations.CostCenter: "42"
    displayName: ${var.ai_data_platform_display_name}
    freeformTags:
      Department: Finance
    isEnableAiFeature: ${var.ai_data_platform_is_enable_ai_feature}
    systemTags: ${var.ai_data_platform_system_tags}
    vectorDbAdminCred: ${var.ai_data_platform_vector_db_admin_cred}
    vectorDbAdminSecretIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_secret
    vectorDbId: ${oci_ai_data_platform_vector_db.test_vector_db.id}
