apiVersion: artifacts.oci.upbound.io/v1alpha1
kind: Repository
metadata:
  annotations:
    meta.upbound.io/example-id: artifacts/v1alpha1/repository
  labels:
    testing.upbound.io/example-name: test_repository
  name: test-repository
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    definedTags:
      Operations.CostCenter: "42"
    description: ${var.repository_description}
    displayName: ${var.repository_display_name}
    freeformTags:
      Department: Finance
    isImmutable: ${var.repository_is_immutable}
    repositoryType: ${var.repository_repository_type}
