apiVersion: identity.oci.upbound.io/v1alpha1
kind: Compartment
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/compartment
  labels:
    testing.upbound.io/example-name: test_compartment
  name: test-compartment
spec:
  forProvider:
    compartmentId: ${var.compartment_id}
    definedTags:
      Operations.CostCenter: "42"
    description: ${var.compartment_description}
    freeformTags:
      Department: Finance
    name: ${var.compartment_name}
