apiVersion: identity.oci.upbound.io/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/group
  labels:
    testing.upbound.io/example-name: test_group
  name: test-group
spec:
  forProvider:
    compartmentId: ${var.tenancy_ocid}
    definedTags:
      Operations.CostCenter: "42"
    description: ${var.group_description}
    freeformTags:
      Department: Finance
    name: ${var.group_name}
