apiVersion: objectstorage.oci.upbound.io/v1alpha1
kind: Bucket
metadata:
  name: bucket-via-crossplane4
spec:
  forProvider:
    # reference compartment by CrossPlaned managed compartment name or OCI compartment OCID
    # a) reference by a CrossPlane managed compartment name using compartmentIdRef
    # For example, metadata.name of compartment created by examples/compartment/compartment.yaml
    compartmentIdRef:
      name : compartment-via-crossplane1
    # or
    # b) compartmentId to reference by OCI compartment OCID using compartmentId
    # change to your OCID
    #compartmentId: "ocid1.compartment.oc1..aaaaaaaa27osxeaezldayzzq5dfwszeg5iscqbbjzcehf3zhoqbi4hx6yb5q"
    name: bucket-via-crossplane
    # change to your OCI object storage namespace
    namespace: "id8pypxcqtqs"