apiVersion: loadbalancer.oci.upbound.io/v1alpha1
kind: Backend
metadata:
  name: lbbackend-via-crossplane
spec:
  forProvider:
    loadBalancerIdRef:
      name: loadbalancer-via-crossplane
    backendsetNameRef:
      name: lbbackendset-via-crossplane
    ipAddress: "10.0.0.20"
    port: 10