apiVersion: loadbalancer.oci.upbound.io/v1alpha1
kind: LoadBalancer
metadata:
  name: loadbalancer-via-crossplane
spec:
  forProvider:
    compartmentIdRef:
      name: compartment-via-crossplane
    displayName: "alwaysFreeLoadBalancer"
    shape: "flexible"
    subnetIdsRefs:
      - name: subnet-via-crossplane
    shapeDetails:
      - maximumBandwidthInMbps: 10
        minimumBandwidthInMbps: 10
