apiVersion: loadbalancer.oci.upbound.io/v1alpha1
kind: RoutingPolicy
metadata:
  name: lbroutingpolicy
spec:
  forProvider:
    loadBalancerIdRef:
      name: loadbalancer-via-crossplane
    conditionLanguageVersion: "V1"
    name: "lbroutingpolicy"
    rules:
      - name: "example_routing_rules"
        condition: "all(http.request.url.path eq (i ''))"
        actions:
          - name: "FORWARD_TO_BACKENDSET"
            backendSetName: "lbbackendset-via-crossplane"