apiVersion: loadbalancer.oci.upbound.io/v1alpha1
kind: RuleSet
metadata:
  name: lbruleset
spec:
  forProvider:
    loadBalancerIdRef:
      name: loadbalancer-via-crossplane
    name: "lbruleset"
    items:
      - action: "ADD_HTTP_REQUEST_HEADER"
        header: "example_header_name"
        value: "example_header_value"