apiVersion: core.oci.upbound.io/v1alpha1
kind: ClusterNetwork
metadata:
  annotations:
    meta.upbound.io/example-id: core/v1alpha1/clusternetwork
  labels:
    testing.upbound.io/example-name: test_cluster_network
  name: test-cluster-network
spec:
  forProvider:
    compartmentId: ${var.compartment_id}
    definedTags:
      Operations.CostCenter: "42"
    displayName: ${var.cluster_network_display_name}
    freeformTags:
      Department: Finance
    instancePools:
    - definedTags:
        Operations.CostCenter: "42"
      displayName: ${var.cluster_network_instance_pools_display_name}
      freeformTags:
        Department: Finance
      instanceConfigurationId: ${oci_core_instance_configuration.test_instance_configuration.id}
      size: ${var.cluster_network_instance_pools_size}
    placementConfiguration:
    - availabilityDomain: ${var.cluster_network_placement_configuration_availability_domain}
      primarySubnetId: ${oci_core_subnet.test_subnet.id}
      secondaryVnicSubnets:
      - displayName: ${var.cluster_network_placement_configuration_secondary_vnic_subnets_display_name}
        subnetId: ${oci_core_subnet.test_subnet.id}
