apiVersion: core.oci.upbound.io/v1alpha1
kind: Volume
metadata:
  annotations:
    meta.upbound.io/example-id: core/v1alpha1/volume
  labels:
    testing.upbound.io/example-name: test_volume
  name: test-volume
spec:
  forProvider:
    autotunePolicies:
    - autotuneType: ${var.volume_autotune_policies_autotune_type}
      maxVpusPerGb: ${var.volume_autotune_policies_max_vpus_per_gb}
    availabilityDomain: ${var.volume_availability_domain}
    backupPolicyId: ${data.oci_core_volume_backup_policies.test_volume_backup_policies.volume_backup_policies.0.id}
    blockVolumeReplicas:
    - availabilityDomain: ${var.volume_block_volume_replicas_availability_domain}
      displayName: ${var.volume_block_volume_replicas_display_name}
    blockVolumeReplicasDeletion: true
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    definedTags:
      Operations.CostCenter: "42"
    displayName: ${var.volume_display_name}
    freeformTags:
      Department: Finance
    isAutoTuneEnabled: ${var.volume_is_auto_tune_enabled}
    kmsKeyId: ${oci_kms_key.test_key.id}
    sizeInGbs: ${var.volume_size_in_gbs}
    sizeInMbs: ${var.volume_size_in_mbs}
    sourceDetails:
    - id: ${var.volume_source_details_id}
      type: ${var.volume_source_details_type}
    vpusPerGb: ${var.volume_vpus_per_gb}
