apiVersion: core.oci.upbound.io/v1alpha1
kind: Vcn
metadata:
  name: vcn-via-crossplane5
spec:
  forProvider:
    compartmentIdRef: 
      name : compartment-via-crossplane1
    displayName: vcn-via-crossplane
    cidrBlocks: ["10.20.20.0/29"]