apiVersion: dns.oci.upbound.io/v1alpha1
kind: Zone
metadata:
  annotations:
    meta.upbound.io/example-id: dns/v1alpha1/zone
  labels:
    testing.upbound.io/example-name: test_zone
  name: test-zone
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    definedTags: ${var.zone_defined_tags}
    dnssecState: ${var.zone_dnssec_state}
    externalDownstreams:
    - address: ${var.zone_external_downstreams_address}
      port: ${var.zone_external_downstreams_port}
      tsigKeyId: ${oci_dns_tsig_key.test_tsig_key.id}
    externalMasters:
    - address: ${var.zone_external_masters_address}
      port: ${var.zone_external_masters_port}
      tsigKeyId: ${oci_dns_tsig_key.test_tsig_key.id}
    freeformTags: ${var.zone_freeform_tags}
    name: ${var.zone_name}
    scope: ${var.zone_scope}
    viewIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_view
    zoneType: ${var.zone_zone_type}
