apiVersion: loadbalancer.oci.upbound.io/v1alpha1
kind: Backend
metadata:
  annotations:
    meta.upbound.io/example-id: loadbalancer/v1alpha1/backend
  labels:
    testing.upbound.io/example-name: test_backend
  name: test-backend
spec:
  forProvider:
    backendsetNameSelector:
      matchLabels:
        testing.upbound.io/example-name: test_backend_set
    backup: ${var.backend_backup}
    drain: ${var.backend_drain}
    ipAddress: ${var.backend_ip_address}
    loadBalancerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_load_balancer
    maxConnections: ${var.backend_max_connections}
    offline: ${var.backend_offline}
    port: ${var.backend_port}
    weight: ${var.backend_weight}
