apiVersion: loadbalancer.oci.upbound.io/v1alpha1
kind: LoadBalancer
metadata:
  annotations:
    meta.upbound.io/example-id: loadbalancer/v1alpha1/loadbalancer
  labels:
    testing.upbound.io/example-name: test_load_balancer
  name: test-load-balancer
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    definedTags:
      Operations.CostCenter: "42"
    displayName: ${var.load_balancer_display_name}
    freeformTags:
      Department: Finance
    ipMode: ${var.load_balancer_ip_mode}
    ipv6subnetCidr: ${var.load_balancer_ipv6subnet_cidr}
    isDeleteProtectionEnabled: ${var.load_balancer_is_delete_protection_enabled}
    isPrivate: ${var.load_balancer_is_private}
    isRequestIdEnabled: ${var.load_balancer_is_request_id_enabled}
    networkSecurityGroupIds: ${var.load_balancer_network_security_group_ids}
    requestIdHeader: ${var.load_balancer_request_id_header}
    reservedIps:
    - id: ${var.load_balancer_reserved_ips_id}
    securityAttributes: ${var.load_balancer_security_attributes}
    shape: ${var.load_balancer_shape}
    shapeDetails:
    - maximumBandwidthInMbps: ${var.load_balancer_shape_details_maximum_bandwidth_in_mbps}
      minimumBandwidthInMbps: ${var.load_balancer_shape_details_minimum_bandwidth_in_mbps}
    subnetIdsSelector:
      matchLabels:
        testing.upbound.io/example-name: example
