apiVersion: loadbalancer.oci.upbound.io/v1alpha1
kind: RuleSet
metadata:
  annotations:
    meta.upbound.io/example-id: loadbalancer/v1alpha1/ruleset
  labels:
    testing.upbound.io/example-name: test_rule_set
  name: test-rule-set
spec:
  forProvider:
    items:
    - action: ${var.rule_set_items_action}
      allowedMethods: ${var.rule_set_items_allowed_methods}
      areInvalidCharactersAllowed: ${var.rule_set_items_are_invalid_characters_allowed}
      conditions:
      - attributeName: ${var.rule_set_items_conditions_attribute_name}
        attributeValue: ${var.rule_set_items_conditions_attribute_value}
        operator: ${var.rule_set_items_conditions_operator}
      defaultMaxConnections: ${var.rule_set_items_default_max_connections}
      description: ${var.rule_set_items_description}
      header: ${var.rule_set_items_header}
      httpLargeHeaderSizeInKb: ${var.rule_set_items_http_large_header_size_in_kb}
      ipMaxConnections:
      - ipAddresses: ${var.rule_set_items_ip_max_connections_ip_addresses}
        maxConnections: ${var.rule_set_items_ip_max_connections_max_connections}
      prefix: ${var.rule_set_items_prefix}
      redirectUri:
      - host: ${var.rule_set_items_redirect_uri_host}
        path: ${var.rule_set_items_redirect_uri_path}
        port: ${var.rule_set_items_redirect_uri_port}
        protocol: ${var.rule_set_items_redirect_uri_protocol}
        query: ${var.rule_set_items_redirect_uri_query}
      responseCode: ${var.rule_set_items_response_code}
      statusCode: ${var.rule_set_items_status_code}
      suffix: ${var.rule_set_items_suffix}
      value: ${var.rule_set_items_value}
    loadBalancerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_load_balancer
    name: ${var.rule_set_name}
