apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositecontainerengines.oci.upbound.io
spec:
  group: oci.jet.crossplane.io
  names:
    kind: CompositeContainerEngine
    plural: compositecontainerengines
  claimNames:
    kind: SimpleOkeCluster
    plural: simpleokeclusters
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  name:
                    type: string
                required:
                - name
            required:
            - parameters
          status:
            type: object
            properties:
              privateSubnetId:
                description: private subnet OCID
                type: string
              igId:
                description : Internet Gateway id
                type: string 
              defaultDHCPOptionsId:
                description : DHCP Options Id
                type: string 