apiVersion: core.oci.upbound.io/v1alpha1
kind: Instance
metadata:
  name: instance-flex-shape-via-crossplane
spec:
  forProvider:
    compartmentIdRef:
      name : compartment-via-crossplane1-amit
    createVnicDetails:
      - subnetIdRef:
          name : subnet-via-crossplane1-amit
    availabilityDomain: "KiJR:PHX-AD-1"
    shape: "VM.Standard.E4.Flex"
    shapeConfig:
      - memoryInGbs: 16
        ocpus: 1
    sourceDetails:
      - sourceId: ocid1.image.oc1.phx.xxx
        sourceType: "image"
    displayName: instance-flex-shape-via-crossplane