apiVersion: core.oci.upbound.io/v1alpha1
kind: PublicIPPoolCapacity
metadata:
  name: public-ip-pool-capacity-via-crossplane
spec:
  forProvider:
    publicIpPoolIdRef:
      name: public-ip-pool-via-crossplane
    byoipId: ocid1.byoiprange.oc1.phx.xxx
    cidrBlock: 10.0.1.0/24