apiVersion: core.oci.upbound.io/v1alpha1
kind: RemotePeeringConnection
metadata:
  name: remote-peering-connection-via-crossplane
spec:
  forProvider:
    compartmentIdRef:
      name : compartment-via-crossplane1
    drgIdRef:
      name: drg-via-crossplanebv v 