apiVersion: kms.oci.upbound.io/v1alpha1
kind: KeyVersion
metadata:
  annotations:
    meta.upbound.io/example-id: kms/v1alpha1/keyversion
  labels:
    testing.upbound.io/example-name: test_key_version
  name: test-key-version
spec:
  forProvider:
    externalKeyVersionId: ${oci_kms_key_version.test_key_version.id}
    keyIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_key
    managementEndpoint: ${var.key_version_management_endpoint}
