apiVersion: kms.oci.upbound.io/v1alpha1
kind: Vault
metadata:
  annotations:
    meta.upbound.io/example-id: kms/v1alpha1/vault
  labels:
    testing.upbound.io/example-name: test_vault
  name: test-vault
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    definedTags:
      Operations.CostCenter: "42"
    displayName: ${var.vault_display_name}
    externalKeyManagerMetadata:
    - externalVaultEndpointUrl: ${var.vault_external_key_manager_metadata_external_vault_endpoint_url}
      oauthMetadata:
      - clientAppId: ${oci_kms_client_app.test_client_app.id}
        clientAppSecret: ${var.vault_external_key_manager_metadata_oauth_metadata_client_app_secret}
        idcsAccountNameUrl: ${var.vault_external_key_manager_metadata_oauth_metadata_idcs_account_name_url}
      privateEndpointId: ${oci_dataflow_private_endpoint.test_private_endpoint.id}
    freeformTags:
      Department: Finance
    vaultType: ${var.vault_vault_type}
