/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ExportInitParameters struct {

	// (Updatable) Export options for the new export. For exports of mount targets with IPv4 address, if client options are left unspecified, client options would default to:
	ExportOptions []ExportOptionsInitParameters `json:"exportOptions,omitempty" tf:"export_options,omitempty"`

	// The OCID of this export's export set.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/filestorage/v1alpha1.ExportSet
	ExportSetID *string `json:"exportSetId,omitempty" tf:"export_set_id,omitempty"`

	// Reference to a ExportSet in filestorage to populate exportSetId.
	// +kubebuilder:validation:Optional
	ExportSetIDRef *v1.Reference `json:"exportSetIdRef,omitempty" tf:"-"`

	// Selector for a ExportSet in filestorage to populate exportSetId.
	// +kubebuilder:validation:Optional
	ExportSetIDSelector *v1.Selector `json:"exportSetIdSelector,omitempty" tf:"-"`

	// The OCID of this export's file system.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/filestorage/v1alpha1.FileSystem
	FileSystemID *string `json:"fileSystemId,omitempty" tf:"file_system_id,omitempty"`

	// Reference to a FileSystem in filestorage to populate fileSystemId.
	// +kubebuilder:validation:Optional
	FileSystemIDRef *v1.Reference `json:"fileSystemIdRef,omitempty" tf:"-"`

	// Selector for a FileSystem in filestorage to populate fileSystemId.
	// +kubebuilder:validation:Optional
	FileSystemIDSelector *v1.Selector `json:"fileSystemIdSelector,omitempty" tf:"-"`

	// (Updatable) Whether or not the export should use ID mapping for Unix groups rather than the group list provided within an NFS request's RPC header. When this flag is true the Unix UID from the RPC header is used to retrieve the list of secondary groups from a the ID mapping subsystem. The primary GID is always taken from the RPC header. If ID mapping is not configured, incorrectly configured, unavailable, or cannot be used to determine a list of secondary groups then an empty secondary group list is used for authorization. If the number of groups exceeds the limit of 256 groups, the list retrieved from LDAP is truncated to the first 256 groups read.
	IsIdmapGroupsForSysAuth *bool `json:"isIdmapGroupsForSysAuth,omitempty" tf:"is_idmap_groups_for_sys_auth,omitempty"`

	IsLockOverride *bool `json:"isLockOverride,omitempty" tf:"is_lock_override,omitempty"`

	// Locks associated with this resource.
	Locks []LocksInitParameters `json:"locks,omitempty" tf:"locks,omitempty"`

	// Path used to access the associated file system.
	Path *string `json:"path,omitempty" tf:"path,omitempty"`
}

type ExportObservation struct {

	// (Updatable) Export options for the new export. For exports of mount targets with IPv4 address, if client options are left unspecified, client options would default to:
	ExportOptions []ExportOptionsObservation `json:"exportOptions,omitempty" tf:"export_options,omitempty"`

	// The OCID of this export's export set.
	ExportSetID *string `json:"exportSetId,omitempty" tf:"export_set_id,omitempty"`

	// The OCID of this export's file system.
	FileSystemID *string `json:"fileSystemId,omitempty" tf:"file_system_id,omitempty"`

	// The OCID of this export.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Updatable) Whether or not the export should use ID mapping for Unix groups rather than the group list provided within an NFS request's RPC header. When this flag is true the Unix UID from the RPC header is used to retrieve the list of secondary groups from a the ID mapping subsystem. The primary GID is always taken from the RPC header. If ID mapping is not configured, incorrectly configured, unavailable, or cannot be used to determine a list of secondary groups then an empty secondary group list is used for authorization. If the number of groups exceeds the limit of 256 groups, the list retrieved from LDAP is truncated to the first 256 groups read.
	IsIdmapGroupsForSysAuth *bool `json:"isIdmapGroupsForSysAuth,omitempty" tf:"is_idmap_groups_for_sys_auth,omitempty"`

	IsLockOverride *bool `json:"isLockOverride,omitempty" tf:"is_lock_override,omitempty"`

	// Locks associated with this resource.
	Locks []LocksObservation `json:"locks,omitempty" tf:"locks,omitempty"`

	// Path used to access the associated file system.
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// The current state of this export.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// When the lock was created.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`
}

type ExportOptionsInitParameters struct {

	// (Updatable) Type of access to grant clients using the file system through this export. If unspecified defaults to READ_WRITE.
	Access *string `json:"access,omitempty" tf:"access,omitempty"`

	// (Updatable) Array of allowed NFS authentication types.
	AllowedAuth []*string `json:"allowedAuth,omitempty" tf:"allowed_auth,omitempty"`

	// (Updatable) GID value to remap to when squashing a client GID (see identitySquash for more details.) If unspecified defaults to 65534.
	AnonymousGID *string `json:"anonymousGid,omitempty" tf:"anonymous_gid,omitempty"`

	// (Updatable) UID value to remap to when squashing a client UID (see identitySquash for more details.) If unspecified, defaults to 65534.
	AnonymousUID *string `json:"anonymousUid,omitempty" tf:"anonymous_uid,omitempty"`

	// (Updatable) Used when clients accessing the file system through this export have their UID and GID remapped to 'anonymousUid' and 'anonymousGid'. If ALL, all users and groups are remapped; if ROOT, only the root user and group (UID/GID 0) are remapped; if NONE, no remapping is done. If unspecified, defaults to ROOT.
	IdentitySquash *string `json:"identitySquash,omitempty" tf:"identity_squash,omitempty"`

	// (Updatable) Whether or not to enable anonymous access to the file system through this export in cases where a user isn't found in the LDAP server used for ID mapping. If true, and the user is not found in the LDAP directory, the operation uses the Squash UID and Squash GID.
	IsAnonymousAccessAllowed *bool `json:"isAnonymousAccessAllowed,omitempty" tf:"is_anonymous_access_allowed,omitempty"`

	// (Updatable) If true, clients accessing the file system through this export must connect from a privileged source port. If unspecified, defaults to true.
	RequirePrivilegedSourcePort *bool `json:"requirePrivilegedSourcePort,omitempty" tf:"require_privileged_source_port,omitempty"`

	// (Updatable) Clients these options should apply to. Must be a either single IPv4 address or single IPv4 CIDR block.
	Source *string `json:"source,omitempty" tf:"source,omitempty"`
}

type ExportOptionsObservation struct {

	// (Updatable) Type of access to grant clients using the file system through this export. If unspecified defaults to READ_WRITE.
	Access *string `json:"access,omitempty" tf:"access,omitempty"`

	// (Updatable) Array of allowed NFS authentication types.
	AllowedAuth []*string `json:"allowedAuth,omitempty" tf:"allowed_auth,omitempty"`

	// (Updatable) GID value to remap to when squashing a client GID (see identitySquash for more details.) If unspecified defaults to 65534.
	AnonymousGID *string `json:"anonymousGid,omitempty" tf:"anonymous_gid,omitempty"`

	// (Updatable) UID value to remap to when squashing a client UID (see identitySquash for more details.) If unspecified, defaults to 65534.
	AnonymousUID *string `json:"anonymousUid,omitempty" tf:"anonymous_uid,omitempty"`

	// (Updatable) Used when clients accessing the file system through this export have their UID and GID remapped to 'anonymousUid' and 'anonymousGid'. If ALL, all users and groups are remapped; if ROOT, only the root user and group (UID/GID 0) are remapped; if NONE, no remapping is done. If unspecified, defaults to ROOT.
	IdentitySquash *string `json:"identitySquash,omitempty" tf:"identity_squash,omitempty"`

	// (Updatable) Whether or not to enable anonymous access to the file system through this export in cases where a user isn't found in the LDAP server used for ID mapping. If true, and the user is not found in the LDAP directory, the operation uses the Squash UID and Squash GID.
	IsAnonymousAccessAllowed *bool `json:"isAnonymousAccessAllowed,omitempty" tf:"is_anonymous_access_allowed,omitempty"`

	// (Updatable) If true, clients accessing the file system through this export must connect from a privileged source port. If unspecified, defaults to true.
	RequirePrivilegedSourcePort *bool `json:"requirePrivilegedSourcePort,omitempty" tf:"require_privileged_source_port,omitempty"`

	// (Updatable) Clients these options should apply to. Must be a either single IPv4 address or single IPv4 CIDR block.
	Source *string `json:"source,omitempty" tf:"source,omitempty"`
}

type ExportOptionsParameters struct {

	// (Updatable) Type of access to grant clients using the file system through this export. If unspecified defaults to READ_WRITE.
	// +kubebuilder:validation:Optional
	Access *string `json:"access,omitempty" tf:"access,omitempty"`

	// (Updatable) Array of allowed NFS authentication types.
	// +kubebuilder:validation:Optional
	AllowedAuth []*string `json:"allowedAuth,omitempty" tf:"allowed_auth,omitempty"`

	// (Updatable) GID value to remap to when squashing a client GID (see identitySquash for more details.) If unspecified defaults to 65534.
	// +kubebuilder:validation:Optional
	AnonymousGID *string `json:"anonymousGid,omitempty" tf:"anonymous_gid,omitempty"`

	// (Updatable) UID value to remap to when squashing a client UID (see identitySquash for more details.) If unspecified, defaults to 65534.
	// +kubebuilder:validation:Optional
	AnonymousUID *string `json:"anonymousUid,omitempty" tf:"anonymous_uid,omitempty"`

	// (Updatable) Used when clients accessing the file system through this export have their UID and GID remapped to 'anonymousUid' and 'anonymousGid'. If ALL, all users and groups are remapped; if ROOT, only the root user and group (UID/GID 0) are remapped; if NONE, no remapping is done. If unspecified, defaults to ROOT.
	// +kubebuilder:validation:Optional
	IdentitySquash *string `json:"identitySquash,omitempty" tf:"identity_squash,omitempty"`

	// (Updatable) Whether or not to enable anonymous access to the file system through this export in cases where a user isn't found in the LDAP server used for ID mapping. If true, and the user is not found in the LDAP directory, the operation uses the Squash UID and Squash GID.
	// +kubebuilder:validation:Optional
	IsAnonymousAccessAllowed *bool `json:"isAnonymousAccessAllowed,omitempty" tf:"is_anonymous_access_allowed,omitempty"`

	// (Updatable) If true, clients accessing the file system through this export must connect from a privileged source port. If unspecified, defaults to true.
	// +kubebuilder:validation:Optional
	RequirePrivilegedSourcePort *bool `json:"requirePrivilegedSourcePort,omitempty" tf:"require_privileged_source_port,omitempty"`

	// (Updatable) Clients these options should apply to. Must be a either single IPv4 address or single IPv4 CIDR block.
	// +kubebuilder:validation:Optional
	Source *string `json:"source" tf:"source,omitempty"`
}

type ExportParameters struct {

	// (Updatable) Export options for the new export. For exports of mount targets with IPv4 address, if client options are left unspecified, client options would default to:
	// +kubebuilder:validation:Optional
	ExportOptions []ExportOptionsParameters `json:"exportOptions,omitempty" tf:"export_options,omitempty"`

	// The OCID of this export's export set.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/filestorage/v1alpha1.ExportSet
	// +kubebuilder:validation:Optional
	ExportSetID *string `json:"exportSetId,omitempty" tf:"export_set_id,omitempty"`

	// Reference to a ExportSet in filestorage to populate exportSetId.
	// +kubebuilder:validation:Optional
	ExportSetIDRef *v1.Reference `json:"exportSetIdRef,omitempty" tf:"-"`

	// Selector for a ExportSet in filestorage to populate exportSetId.
	// +kubebuilder:validation:Optional
	ExportSetIDSelector *v1.Selector `json:"exportSetIdSelector,omitempty" tf:"-"`

	// The OCID of this export's file system.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/filestorage/v1alpha1.FileSystem
	// +kubebuilder:validation:Optional
	FileSystemID *string `json:"fileSystemId,omitempty" tf:"file_system_id,omitempty"`

	// Reference to a FileSystem in filestorage to populate fileSystemId.
	// +kubebuilder:validation:Optional
	FileSystemIDRef *v1.Reference `json:"fileSystemIdRef,omitempty" tf:"-"`

	// Selector for a FileSystem in filestorage to populate fileSystemId.
	// +kubebuilder:validation:Optional
	FileSystemIDSelector *v1.Selector `json:"fileSystemIdSelector,omitempty" tf:"-"`

	// (Updatable) Whether or not the export should use ID mapping for Unix groups rather than the group list provided within an NFS request's RPC header. When this flag is true the Unix UID from the RPC header is used to retrieve the list of secondary groups from a the ID mapping subsystem. The primary GID is always taken from the RPC header. If ID mapping is not configured, incorrectly configured, unavailable, or cannot be used to determine a list of secondary groups then an empty secondary group list is used for authorization. If the number of groups exceeds the limit of 256 groups, the list retrieved from LDAP is truncated to the first 256 groups read.
	// +kubebuilder:validation:Optional
	IsIdmapGroupsForSysAuth *bool `json:"isIdmapGroupsForSysAuth,omitempty" tf:"is_idmap_groups_for_sys_auth,omitempty"`

	// +kubebuilder:validation:Optional
	IsLockOverride *bool `json:"isLockOverride,omitempty" tf:"is_lock_override,omitempty"`

	// Locks associated with this resource.
	// +kubebuilder:validation:Optional
	Locks []LocksParameters `json:"locks,omitempty" tf:"locks,omitempty"`

	// Path used to access the associated file system.
	// +kubebuilder:validation:Optional
	Path *string `json:"path,omitempty" tf:"path,omitempty"`
}

type LocksInitParameters struct {

	// A message added by the creator of the lock. This is typically used to give an indication of why the resource is locked.
	Message *string `json:"message,omitempty" tf:"message,omitempty"`

	// The ID of the resource that is locking this resource. Indicates that deleting this resource will remove the lock.
	RelatedResourceID *string `json:"relatedResourceId,omitempty" tf:"related_resource_id,omitempty"`

	// When the lock was created.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// Type of the lock.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type LocksObservation struct {

	// A message added by the creator of the lock. This is typically used to give an indication of why the resource is locked.
	Message *string `json:"message,omitempty" tf:"message,omitempty"`

	// The ID of the resource that is locking this resource. Indicates that deleting this resource will remove the lock.
	RelatedResourceID *string `json:"relatedResourceId,omitempty" tf:"related_resource_id,omitempty"`

	// When the lock was created.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// Type of the lock.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type LocksParameters struct {

	// A message added by the creator of the lock. This is typically used to give an indication of why the resource is locked.
	// +kubebuilder:validation:Optional
	Message *string `json:"message,omitempty" tf:"message,omitempty"`

	// The ID of the resource that is locking this resource. Indicates that deleting this resource will remove the lock.
	// +kubebuilder:validation:Optional
	RelatedResourceID *string `json:"relatedResourceId,omitempty" tf:"related_resource_id,omitempty"`

	// When the lock was created.
	// +kubebuilder:validation:Optional
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// Type of the lock.
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

// ExportSpec defines the desired state of Export
type ExportSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ExportParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ExportInitParameters `json:"initProvider,omitempty"`
}

// ExportStatus defines the observed state of Export.
type ExportStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ExportObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Export is the Schema for the Exports API. Provides the Export resource in Oracle Cloud Infrastructure File Storage service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type Export struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.path) || (has(self.initProvider) && has(self.initProvider.path))",message="spec.forProvider.path is a required parameter"
	Spec   ExportSpec   `json:"spec"`
	Status ExportStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ExportList contains a list of Exports
type ExportList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Export `json:"items"`
}

// Repository type metadata.
var (
	Export_Kind             = "Export"
	Export_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Export_Kind}.String()
	Export_KindAPIVersion   = Export_Kind + "." + CRDGroupVersion.String()
	Export_GroupVersionKind = CRDGroupVersion.WithKind(Export_Kind)
)

func init() {
	SchemeBuilder.Register(&Export{}, &ExportList{})
}
