apiVersion: cloudmigrations.oci.upbound.io/v1alpha1
kind: MigrationAsset
metadata:
  annotations:
    meta.upbound.io/example-id: cloudmigrations/v1alpha1/migrationasset
  labels:
    testing.upbound.io/example-name: test_migration_asset
  name: test-migration-asset
spec:
  forProvider:
    availabilityDomain: ${var.migration_asset_availability_domain}
    displayName: ${var.migration_asset_display_name}
    inventoryAssetId: ${var.inventory_asset_id}
    migrationAssetDependsOn: ${var.migration_asset_migration_asset_depends_on}
    migrationIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_migration
    replicationCompartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_compartment
    replicationLocationDetail:
    - metadata: ${var.migration_asset_replication_location_detail_metadata}
      replicationLocationType: ${var.migration_asset_replication_location_detail_replication_location_type}
    replicationScheduleIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_replication_schedule
    snapShotBucketNameSelector:
      matchLabels:
        testing.upbound.io/example-name: test_bucket
