apiVersion: clusterhealth.oci.upbound.io/v1alpha1
kind: DiagnosisStore
metadata:
  annotations:
    meta.upbound.io/example-id: clusterhealth/v1alpha1/diagnosisstore
  labels:
    testing.upbound.io/example-name: test_diagnosis_store
  name: test-diagnosis-store
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    definedTags:
      Operations.CostCenter: "42"
    displayName: ${var.diagnosis_store_display_name}
    freeformTags:
      Department: Finance
    objectStoreBucket: ${var.diagnosis_store_object_store_bucket}
    objectStoreNamespace: ${var.diagnosis_store_object_store_namespace}
