apiVersion: networkconnectivity.oci.upbound.io/v1alpha1
kind: CrossConnect
metadata:
  annotations:
    meta.upbound.io/example-id: networkconnectivity/v1alpha1/crossconnect
  labels:
    testing.upbound.io/example-name: test_cross_connect
  name: test-cross-connect
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    crossConnectGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_cross_connect_group
    customerReferenceName: ${var.cross_connect_customer_reference_name}
    definedTags:
      Operations.CostCenter: "42"
    displayName: ${var.cross_connect_display_name}
    farCrossConnectOrCrossConnectGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_cross_connect_group
    freeformTags:
      Department: Finance
    interfaceDownTimerValueInMilliseconds: ${var.cross_connect_interface_down_timer_value_in_milliseconds}
    interfaceName: ${var.cross_connect_interface_name}
    isInterfaceHoldTimerEnabled: ${var.cross_connect_is_interface_hold_timer_enabled}
    isQosEnabled: ${var.cross_connect_is_qos_enabled}
    loaProperties:
    - authorizedAgent: ${var.cross_connect_loa_properties_authorized_agent}
    locationName: ${var.cross_connect_location_name}
    macsecProperties:
    - encryptionCipher: ${var.cross_connect_macsec_properties_encryption_cipher}
      isUnprotectedTrafficAllowed: ${var.cross_connect_macsec_properties_is_unprotected_traffic_allowed}
      primaryKey:
      - connectivityAssociationKeySecretIdSelector:
          matchLabels:
            testing.upbound.io/example-name: test_secret
        connectivityAssociationNameSecretIdSelector:
          matchLabels:
            testing.upbound.io/example-name: test_secret
      state: ${var.cross_connect_macsec_properties_state}
    nearCrossConnectOrCrossConnectGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_cross_connect_group
    ociPhysicalDeviceName: ${var.cross_connect_oci_physical_device_name}
    portSpeedShapeName: ${var.cross_connect_port_speed_shape_name}
