apiVersion: networkconnectivity.oci.upbound.io/v1alpha1
kind: CrossConnectGroup
metadata:
  annotations:
    meta.upbound.io/example-id: networkconnectivity/v1alpha1/crossconnectgroup
  labels:
    testing.upbound.io/example-name: test_cross_connect_group
  name: test-cross-connect-group
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    customerReferenceName: ${var.cross_connect_group_customer_reference_name}
    definedTags:
      Operations.CostCenter: "42"
    displayName: ${var.cross_connect_group_display_name}
    freeformTags:
      Department: Finance
    interfaceDownTimerValueInMilliseconds: ${var.cross_connect_group_interface_down_timer_value_in_milliseconds}
    isInterfaceHoldTimerEnabled: ${var.cross_connect_group_is_interface_hold_timer_enabled}
    isQosEnabled: ${var.cross_connect_group_is_qos_enabled}
    macsecProperties:
    - encryptionCipher: ${var.cross_connect_group_macsec_properties_encryption_cipher}
      isUnprotectedTrafficAllowed: ${var.cross_connect_group_macsec_properties_is_unprotected_traffic_allowed}
      primaryKey:
      - connectivityAssociationKeySecretIdSelector:
          matchLabels:
            testing.upbound.io/example-name: test_secret
        connectivityAssociationNameSecretIdSelector:
          matchLabels:
            testing.upbound.io/example-name: test_secret
      state: ${var.cross_connect_group_macsec_properties_state}
    minimumLinks: ${var.cross_connect_group_minimum_links}
