apiVersion: networkconnectivity.oci.upbound.io/v1alpha1
kind: DefaultDrgRouteTable
metadata:
  annotations:
    meta.upbound.io/example-id: networkconnectivity/v1alpha1/defaultdrgroutetable
  labels:
    testing.upbound.io/example-name: default_drg_route_table
  name: default-drg-route-table
spec:
  forProvider:
    definedTags:
      Operations.CostCenter: "42"
    displayName: managed-default-drg-route-table
    freeformTags:
      Department: Finance
    importDrgRouteDistributionIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_drg_route_distribution
    isEcmpEnabled: true
    manageDefaultResourceId: ${oci_core_drg.test_drg.default_drg_route_tables[0].vcn}
