apiVersion: core.oci.upbound.io/v1alpha1
kind: InternetGateway
metadata:
  name: ig-via-crossplane5
spec:
  forProvider:
    compartmentIdRef: 
      name : compartment-via-crossplane5
    vcnIdRef:
      name: vcn-via-crossplane5