apiVersion: core.oci.upbound.io/v1alpha1
kind: IpsecConnectionTunnelManagement
metadata:
  name: test-ip-sec-connection-tunnel-management
spec:
  forProvider:
    ipsecId: ocid1.ipsecconnection.xxx
    tunnelId: ocid1.ipsectunnel.xxx
    bgpSessionInfo:
      - customerBgpAsn: "1587232876"
        customerInterfaceIp: "10.0.0.16/31"
        oracleInterfaceIp: "10.0.0.17/31"
    displayName: "test-ip-sec-connection-tunnel"
    ikeVersion: "V1"
    routing: "BGP"
    sharedSecret: "sharedSecret"
