apiVersion: core.oci.upbound.io/v1alpha1
kind: InstancePool
metadata:
  name: test-instance-pool
spec:
  forProvider:
    compartmentId: ocid1.compartment.xxx
    instanceConfigurationId: ocid1.instanceconfiguration.xxx
    placementConfigurations:
      - availabilityDomain: xxx
        primarySubnetId: ocid1.subnet.oci1.xxx
      - availability_domain: yyy
        primary_subnet_id: "ocid1.subnet.oci1.yyy"
    size: 2
    displayName: test-instance-pool