# Create a private virtual circuit.  See terraform example for other various configurations:
# public, layer2, layer3.
# https://github.com/oracle/terraform-provider-oci/blob/master/examples/fast_connect/virtual_circuit.tf
#
apiVersion: core.oci.upbound.io/v1alpha1
kind: VirtualCircuit
metadata:
  name: test-virtual-circuit
spec:
  forProvider:
    compartmentId:  ocid1.compartment.xxx
    type: "PRIVATE"
    bandwidthShapeName: "1 Gbps"
    crossConnectMappings:
        crossConnectOrCrossConnectGroupId: ocid1.crossconnectgroup.xxx
        customerBgpPeeringIp: "10.0.0.18/31"
        oracleBgpPeeringIp: "10.0.0.19/31"
        vlan: 200
    customerAsn: 10
    displayName: test-virtual-circuit
    gatewayId: ocid1.drg.xxx
    region: us-phoenix-1
