apiVersion: core.oci.upbound.io/v1alpha1
kind: LocalPeeringGateway
metadata:
  name: localpeeringgateway
spec:
  forProvider:
    compartmentIdRef:
      name : compartment-via-crossplane5
    vcnIdRef:
      name: vcn-via-crossplane5
