apiVersion: core.oci.upbound.io/v1alpha1
kind: ClusterNetwork
metadata:
  name: test-cluster-network
spec:
  forProvider:
    compartmentId: ocid1.compartment.xxx
    instancePools:
        displayName: cluster-network-instance-pools
        instanceConfigurationId: ocid1.instanceconfiguration.xxx
        size: '1'
    placementConfiguration:
      - availabilityDomain: xxx
        primarySubnetId: ocid1.subnet.xxx
