apiVersion: core.oci.upbound.io/v1alpha1
kind: Instance
metadata:
  name: test-instance
spec:
  forProvider:
    availabilityDomain: xxx
    compartmentId: ocid1.compartment.xxx
    displayName: test-instance
    shape: "VM.Standard2.1"
    createVnicDetails:
      - assignPrivateDnsRecord: true
        assignPublicIp: "true"
        hostnameLabel: test-instance
        subnetId: ocid1.subnet.oc1.xxx
    shapeConfig:
      - memoryInGbs: 1
        ocpus: 1
    sourceDetails:
      - sourceId: ocid1.image.oc1.xxx
        sourceType: image