apiVersion: database.oci.upbound.io/v1alpha1
kind: AutonomousContainerDatabase
metadata:
  annotations:
    meta.upbound.io/example-id: database/v1alpha1/autonomouscontainerdatabase
  labels:
    testing.upbound.io/example-name: test_autonomous_container_database
  name: test-autonomous-container-database
spec:
  forProvider:
    autonomousContainerDatabaseBackupId: ${oci_database_autonomous_container_database_backup.test_autonomous_container_database_backup.id}
    autonomousDatabasesToClone: ${var.autonomous_container_database_autonomous_databases_to_clone}
    autonomousExadataInfrastructureIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_autonomous_exadata_infrastructure
    autonomousVmClusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_autonomous_vm_cluster
    backupConfig:
    - backupDestinationDetails:
      - backupRetentionPolicyOnTerminate: ${var.autonomous_container_database_backup_config_backup_destination_details_backup_retention_policy_on_terminate}
        dbrs_policy_id: ${oci_identity_policy.test_policy.id}
        id: ${var.autonomous_container_database_backup_config_backup_destination_details_id}
        internetProxy: ${var.autonomous_container_database_backup_config_backup_destination_details_internet_proxy}
        isRemote: ${var.autonomous_container_database_backup_config_backup_destination_details_is_remote}
        isRetentionLockEnabled: ${var.autonomous_container_database_backup_config_backup_destination_details_is_retention_lock_enabled}
        remoteRegion: ${var.autonomous_container_database_backup_config_backup_destination_details_remote_region}
        type: ${var.autonomous_container_database_backup_config_backup_destination_details_type}
        vpcPasswordSecretRef:
          key: example-key
          name: example-secret
          namespace: upbound-system
        vpcUser: ${var.autonomous_container_database_backup_config_backup_destination_details_vpc_user}
      recoveryWindowInDays: ${var.autonomous_container_database_backup_config_recovery_window_in_days}
    cloneBandWidth: ${var.autonomous_container_database_clone_band_width}
    cloneType: ${var.autonomous_container_database_clone_type}
    cloudAutonomousVmClusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_cloud_autonomous_vm_cluster
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    customerContacts:
    - email: ${var.autonomous_container_database_customer_contacts_email}
    databaseSoftwareImageIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_database_software_image
    dbName: ${var.autonomous_container_database_db_name}
    dbSplitThreshold: ${var.autonomous_container_database_db_split_threshold}
    dbUniqueName: ${var.autonomous_container_database_db_unique_name}
    dbVersion: ${var.autonomous_container_database_db_version}
    definedTags:
      Operations.CostCenter: "42"
    displayName: ${var.autonomous_container_database_display_name}
    distributionAffinity: ${var.autonomous_container_database_distribution_affinity}
    encryptionKeyLocationDetails:
    - awsEncryptionKeyIdSelector:
        matchLabels:
          testing.upbound.io/example-name: test_key
      providerType: ${var.autonomous_container_database_encryption_key_location_details_provider_type}
    fastStartFailOverLagLimitInSeconds: ${var.autonomous_container_database_fast_start_fail_over_lag_limit_in_seconds}
    freeformTags:
      Department: Finance
    isAutomaticFailoverEnabled: ${var.autonomous_container_database_is_automatic_failover_enabled}
    isDstFileUpdateEnabled: ${var.autonomous_container_database_is_dst_file_update_enabled}
    keyStoreIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_key_store
    kmsKeyIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_key
    maintenanceWindowDetails:
    - customActionTimeoutInMins: ${var.autonomous_container_database_maintenance_window_details_custom_action_timeout_in_mins}
      daysOfWeek:
      - name: ${var.autonomous_container_database_maintenance_window_details_days_of_week_name}
      hoursOfDay: ${var.autonomous_container_database_maintenance_window_details_hours_of_day}
      isCustomActionTimeoutEnabled: ${var.autonomous_container_database_maintenance_window_details_is_custom_action_timeout_enabled}
      isMonthlyPatchingEnabled: ${var.autonomous_container_database_maintenance_window_details_is_monthly_patching_enabled}
      leadTimeInWeeks: ${var.autonomous_container_database_maintenance_window_details_lead_time_in_weeks}
      months:
      - name: ${var.autonomous_container_database_maintenance_window_details_months_name}
      patchingMode: ${var.autonomous_container_database_maintenance_window_details_patching_mode}
      preference: ${var.autonomous_container_database_maintenance_window_details_preference}
      skipRu: ${var.autonomous_container_database_maintenance_window_details_skip_ru}
      weeksOfMonth: ${var.autonomous_container_database_maintenance_window_details_weeks_of_month}
    netServicesArchitecture: ${var.autonomous_container_database_net_services_architecture}
    okvEndPointGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: test_group
    patchModel: ${var.autonomous_container_database_patch_model}
    peerAutonomousContainerDatabaseBackupConfig:
    - backupDestinationDetails:
      - backupRetentionPolicyOnTerminate: ${var.autonomous_container_database_peer_autonomous_container_database_backup_config_backup_destination_details_backup_retention_policy_on_terminate}
        dbrs_policy_id: ${oci_identity_policy.test_policy.id}
        id: ${var.autonomous_container_database_peer_autonomous_container_database_backup_config_backup_destination_details_id}
        internetProxy: ${var.autonomous_container_database_peer_autonomous_container_database_backup_config_backup_destination_details_internet_proxy}
        isRemote: ${var.autonomous_container_database_peer_autonomous_container_database_backup_config_backup_destination_details_is_remote}
        isRetentionLockEnabled: ${var.autonomous_container_database_peer_autonomous_container_database_backup_config_backup_destination_details_is_retention_lock_enabled}
        remoteRegion: ${var.autonomous_container_database_peer_autonomous_container_database_backup_config_backup_destination_details_remote_region}
        type: ${var.autonomous_container_database_peer_autonomous_container_database_backup_config_backup_destination_details_type}
        vpcPasswordSecretRef:
          key: example-key
          name: example-secret
          namespace: upbound-system
        vpcUser: ${var.autonomous_container_database_peer_autonomous_container_database_backup_config_backup_destination_details_vpc_user}
      recoveryWindowInDays: ${var.autonomous_container_database_peer_autonomous_container_database_backup_config_recovery_window_in_days}
    peerAutonomousContainerDatabaseCompartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_compartment
    peerAutonomousContainerDatabaseDisplayName: ${var.autonomous_container_database_peer_autonomous_container_database_display_name}
    peerAutonomousExadataInfrastructureIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_autonomous_exadata_infrastructure
    peerAutonomousVmClusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_autonomous_vm_cluster
    peerCloudAutonomousVmClusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_cloud_autonomous_vm_cluster
    peerDbUniqueName: ${var.autonomous_container_database_peer_db_unique_name}
    protectionMode: ${var.autonomous_container_database_protection_mode}
    serviceLevelAgreementType: ${var.autonomous_container_database_service_level_agreement_type}
    shouldUseLatestAvailableBackupTimeStamp: ${var.autonomous_container_database_should_use_latest_available_backup_time_stamp}
    source: ${var.autonomous_container_database_source}
    sourceAutonomousContainerDatabaseIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_autonomous_container_database
    standbyMaintenanceBufferInDays: ${var.autonomous_container_database_standby_maintenance_buffer_in_days}
    timeStampToUseForCloning: ${var.autonomous_container_database_time_stamp_to_use_for_cloning}
    vaultIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_vault
    versionPreference: ${var.autonomous_container_database_version_preference}
    vmFailoverReservation: ${var.autonomous_container_database_vm_failover_reservation}
