apiVersion: oda.oci.upbound.io/v1alpha1
kind: OdaPrivateEndpoint
metadata:
  annotations:
    meta.upbound.io/example-id: oda/v1alpha1/odaprivateendpoint
  labels:
    testing.upbound.io/example-name: test_oda_private_endpoint
  name: test-oda-private-endpoint
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    definedTags:
      foo-namespace.bar-key: value
    description: ${var.oda_private_endpoint_description}
    displayName: ${var.oda_private_endpoint_display_name}
    freeformTags:
      bar-key: value
    nsgIds: ${var.oda_private_endpoint_nsg_ids}
    securityAttributes: ${var.oda_private_endpoint_security_attributes}
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_subnet
