apiVersion: resourcescheduler.oci.m.upbound.io/v1alpha1
kind: Schedule
metadata:
  annotations:
    meta.upbound.io/example-id: resourcescheduler/v1alpha1/schedule
  labels:
    testing.upbound.io/example-name: test_schedule
  name: test-schedule
  namespace: upbound-system
spec:
  forProvider:
    action: ${var.schedule_action}
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    definedTags:
      Operations.CostCenter: "42"
    description: ${var.schedule_description}
    displayName: ${var.schedule_display_name}
    freeformTags:
      Department: Finance
    localTimeZone: ${var.schedule_local_time_zone}
    recurrenceDetails: ${var.schedule_recurrence_details}
    recurrenceType: ${var.schedule_recurrence_type}
    resourceFilters:
    - attribute: ${var.schedule_resource_filters_attribute}
      condition: ${var.schedule_resource_filters_condition}
      shouldIncludeChildCompartments: ${var.schedule_resource_filters_should_include_child_compartments}
      value:
      - namespace: ${var.schedule_resource_filters_value_namespace}
        tagKey: ${var.schedule_resource_filters_value_tag_key}
        value: ${var.schedule_resource_filters_value_value}
    resources:
    - id: ${var.schedule_resources_id}
      metadata: ${var.schedule_resources_metadata}
      parameters:
      - parameterType: ${var.schedule_resources_parameters_parameter_type}
        value: ${var.schedule_resources_parameters_value}
    timeEnds: ${var.schedule_time_ends}
    timeStarts: ${var.schedule_time_starts}
