apiVersion: blockstorage.oci.upbound.io/v1alpha1
kind: VolumeGroupBackup
metadata:
  annotations:
    meta.upbound.io/example-id: blockstorage/v1alpha1/volumegroupbackup
  labels:
    testing.upbound.io/example-name: test_volume_group_backup
  name: test-volume-group-backup
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    definedTags:
      Operations.CostCenter: "42"
    displayName: ${var.volume_group_backup_display_name}
    freeformTags:
      Department: Finance
    isIndefiniteRetentionEnabled: ${var.volume_group_backup_is_indefinite_retention_enabled}
    isPreventDeletionEnabled: ${var.volume_group_backup_is_prevent_deletion_enabled}
    isRetentionLockEnabled: ${var.volume_group_backup_is_retention_lock_enabled}
    retentionPeriod:
    - retentionTimeAmount: ${var.volume_group_backup_retention_period_retention_time_amount}
      retentionTimeUnit: ${var.volume_group_backup_retention_period_retention_time_unit}
    type: ${var.volume_group_backup_type}
    volumeGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_volume_group
